food-safety:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: www.ylxteach.net
    port: 3366
    database: food_safety
    username: test
    password: 123456
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tDcF4uikxjUeKuPmdvW
    access-key-secret: 9hL7vxHHbUzHt1P8KfU2AluMBGq6M0
    bucket-name: cangqiongwaimai-yukino
  redis:
    host: localhost
    port: 6379
  wechat:
    appid: wxcf576759ac84951a
    secret: 9e9baeb3f4266a9cff1238aadfb6a666
  ai:
    api-url: https://api.siliconflow.cn/v1/chat/completions
    api-key: sk-kqjtmsrajgjyzkfbprqyifhhakkcvwjfovfrocfioxplsoty
    model: deepseek-ai/DeepSeek-V3
    ocr-url: https://gjbsb.market.alicloudapi.com/ocrservice/advanced
    ocr-app-code: bea4694403894fdc81bd203f6ba5e9a0
