food-safety:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: www.ylxteach.net
    port: 3366
    database: food_safety
    username: test
    password: 123456
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: xxx
    access-key-secret: xxx
    bucket-name: cangqiongwaimai-yukino
  redis:
    host: localhost
    port: 6379
  wechat:
    appid: xxx
    secret: xxx
  ai:
    api-url: xxx
    api-key: xxx
    model: deepseek-ai/DeepSeek-V3
    ocr-url: xxx
    ocr-app-code: xxx
