food-safety:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    host: www.ylxteach.net
    port: 3366
    database: food_safety
    username: test
    password: 123456
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: xxx
    access-key-secret: yyy
    bucket-name: cangqiongwaimai-yukino
  redis:
    host: localhost
    port: 6379
